extends Node


var gallery_data = {
	alexandra_neutral = false,
	alexandra_happy = false,
	alexandra_angry = false,
	alexandra_sad = false,
	loren_neutral = false, 
	loren_happy = false,
	loren_angry = false,
	loren_sad = false,
	archimedes_neutral = false,
	archimedes_happy = false,
	archimedes_sad = false,
	gg_neutral = false,
	gg_happy = false,
	gg_angry = false,
	gg_sad = false,
	whiskerly_neutral = false,
	whiskerly_happy = false,
	whiskerly_sad = false,
	zara_neutral = false,
	zara_happy = false,
	zara_sad = false,
	cafe_background = false,
	ending_background = false,
	cup = false,
	mug = false,
	glass = false,
	coffee = false,
	matcha = false,
	mango = false,
	strawberry = false,
	milk_tea = false,
	catnip = false,
	boba = false,
	cream_and_cat_treats = false,
	magical_mushroom_fish = false
}
